<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Blazor-ApexCharts" Version="6.0.1" />
    <PackageReference Include="Cropper.Blazor" Version="1.4.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.6" />
    <PackageReference Include="MudBlazor" Version="8.8.0" />
    <PackageReference Include="MudBlazor.Markdown" Version="8.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.14.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.14.0" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.14.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlazorAdmin.Data\BlazorAdmin.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\CusCulture.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CusCulture.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\CusCulture.en.resx">
      <SubType>Designer</SubType>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CusCulture.resx">
      <LastGenOutput>CusCulture.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>